### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by fireflamesniper** [xdanieldzd/N3DSCmbViewer#3]
Could you somehow add tga exporting support with this? I know it does it as png but it would be a whole lot helpful if it were tga

**Comment by PwnzLPs** [comment]
Is there a specific reason you need tga exporting? It would be sort-of
difficult to implement from my view point.

**Comment by fireflamesniper** [comment]
I import the objects into the Valve Source Engine ( specifically Garry's Mod and Source Filmmaker Steam Workshops, and the modeling tools I use seem to easily convert a tga into the Valve Texture Files, but as long as they are TGA format files, I mean doing it from Png can be a pain sometimes

**Comment by xdanieldzd** [comment]
.NET does not natively support TGAs (for whatever reason), so adding support for them would mean either finding a library that supports writing TGA files, which would introduce another dependency to the project, or writing my own TGA writer class.

So, while support for the format would be nice in the medium term, I don't really see an immediate need for it, when there's other areas that require more work and research in the short term.

**Comment by einstein95** [comment]
I'm not sure why you couldn't use irfanview's batch converting to convert a
bunch of pngs to tga.

**Comment by fireflamesniper** [comment]
Ah, alright, I'll just use the way I have been getting them to work then

**Comment by fireflamesniper** [comment]
Actually, is bone exporting support coming? I think someone else on steam and I were wondering

**Comment by PwnzLPs** [comment]
That is slowly being worked on. I have been working on this with some
people in Private to get animations viewable and exportable along with bone
structures.

**Comment by fireflamesniper** [comment]
Awesome, can't wait to see animationsanimations

**Comment by fireflamesniper** [comment]
Animations*
