### ISSUE TITLE
Shader Issue/Unsupported Graphics Chipset?

### ISSUE THREAD

**Issue by PwnzLPs** [xdanieldzd/N3DSCmbViewer#4]
Hey xdaniel.

I am unfortunately stuck on my dinosaur of a laptop until further notice, and I am trying to check some stuff out with the MM3D Files, and I get an error every time I try to open a model file. Whether its a map or an actor model, it gives me the same type of error. The most I can get from the error is that it seems to be either a Shader Issue or an Incompatibility Issue with something. Got a screenshot for you. Screens are at the bottom, along with the crash logs (3 or 4). I have separated the crash logs with hyphens, so you shouldn't have a problem telling each one apart. And, whenever I try to close the program after getting the supposed Shader Issue, I get actual errors, about 3, and then the program proceeds to crash. If you could help me fix this, that would be awesome!

Thanks!
/PwnzLPs

![poss_shader_error](https://cloud.githubusercontent.com/assets/8483054/7338103/060c3c66-ec0f-11e4-8c6c-3aa8b3702dbc.png)

ERROR BOX LOG (THEY ARE ALL THE SAME...)
----------------------------------------------------------------------------
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at N3DSCmbViewer.Cmb.ModelHandler.Dispose(Boolean disposing) in C:\Users\Daniel\Documents\Visual Studio 2010\Projects\N3DSCmbViewer\N3DSCmbViewer\Cmb\ModelHandler.cs:line 121
   at N3DSCmbViewer.Cmb.ModelHandler.Dispose() in C:\Users\Daniel\Documents\Visual Studio 2010\Projects\N3DSCmbViewer\N3DSCmbViewer\Cmb\ModelHandler.cs:line 96
   at N3DSCmbViewer.MainForm.MainForm_FormClosing(Object sender, FormClosingEventArgs e) in C:\Users\Daniel\Documents\Visual Studio 2010\Projects\N3DSCmbViewer\N3DSCmbViewer\MainForm.cs:line 219
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
N3DSCmbViewer
    Assembly Version: 0.2.5.0
    Win32 Version: 0.2.5.0
    CodeBase: file:///C:/Users/Ryan/Desktop/3ds_cmb_viewer/N3DSCmbViewer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Aglex
    Assembly Version: 0.0.2.0
    Win32 Version: 0.0.2.0
    CodeBase: file:///C:/Users/Ryan/Desktop/3ds_cmb_viewer/Aglex.DLL
----------------------------------------
OpenTK.GLControl
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1664.6217
    CodeBase: file:///C:/Users/Ryan/Desktop/3ds_cmb_viewer/OpenTK.GLControl.DLL
----------------------------------------
OpenTK
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1664.6217
    CodeBase: file:///C:/Users/Ryan/Desktop/3ds_cmb_viewer/OpenTK.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

----------------------------------------------------------------------------------------------------------------------------

**Comment by xdanieldzd** [comment]
Looks like an incompatibility issue with the graphics chipset of your "dinosaur"; it doesn't support some of the GLSL extensions/functions which are required for, at least, skeletal rendering and animation support, which includes how certain things are placed in maps, if I remember correctly ex. the fountains in MM3D Termina Field.

I could try to write a more rudimentary shader that would support lower-end hardware like your laptop's, although I don't think I'd be able to fully support animation with that (once that even works, if ever). Cannot give an ETA for this, but shouldn't take too long once I start. Also, just for the record, could you give me your OpenGL version and vendor/renderer, so that I have a better idea what GLSL version to target? Find those by starting the viewer, and cycling to the HUD page System Stats (3/3) with F1.

(Also, sorry for the delay in replying!)

**Comment by PwnzLPs** [comment]
No worries. I will go ahead and get the shader info for what you need. I will try to get that to you by Wednesday

**Comment by robotortoise** [comment]
> I could try to write a more rudimentary shader that would support lower-end hardware like your laptop's, although I don't think I'd be able to fully support animation with that (once that even works, if ever). 

Wait, so does this mean you might get animations working?

That'd be awesome, xdaniel! I mean, if you can't, that's cool too, but....

Anyways, if there's anything us #zelda users can do, let me know. I want to help as much as I can!

**Comment by PwnzLPs** [comment]
Sorry for the wait. I've been pretty busy with school, and with shit loads of hard drive failures on my desktop computer, so I haven't gotten a chance to reply. But, I got the pic for you. Sorry for having to take it with my phone. Dinosaur is being slow.
![img_20150510_124125026_hdr](https://cloud.githubusercontent.com/assets/8483054/7555229/4edeb5f0-f712-11e4-958e-e43afc61380e.jpg)

**Comment by xdanieldzd** [comment]
robotortoise:
> Wait, so does this mean you might get animations working?
> 
> That'd be awesome, xdaniel! I mean, if you can't, that's cool too, but....

Emphasis on "if ever". I wouldn't count on it, but I'll poke at it from time to time. Maybe I'll have some kind of epiphany someday, get the bugs in the current skeletal rendering code worked out, and then look into actual animations - or maybe I'll try it a few more times and give up because I can't even get an actor's neutral pose to render properly. I do not know.

PwnzLPs:
> Sorry for the wait. [...] But, I got the pic for you.

Okay, OpenGL 2.1, which I believe means GLSL 1.2, so that's something to work with... I'll try and take a stab at implementing a compatible shader eventually, not sure when that'll be, though.

**Comment by PwnzLPs** [comment]
No worries. Take your time! I know your very busy! :)

**Comment by robotortoise** [comment]
Okay, well good luck Xdaniel! If there's anything I can do to help, let me know.
