### ISSUE TITLE
bone/animation support

### ISSUE THREAD

**Issue by ThatGuyIsBack** [xdanieldzd/N3DSCmbViewer#5]
When will exporting bone/animation be added to N3DSCmbViewer?

**Comment by xdanieldzd** [comment]
Not planned for the foreseeable future, for two reasons:

First, a lack of knowledge regarding bones and animation in OoT/MM3D and regarding how to export those to Collada. There is some information out there about how ex. animations work, but I haven't tested any of it, it's probably incomplete, etc.

Second, a lack of interest on my side in OoT/MM3D, and Zelda hacking/modding in general. With a "community" apparently unwilling to learn, drama flaring up every once in a while - OoT3D research *began* with drama, after all! -, and me basically getting bored with the games, it's unlikely I'll be spending much more time on this.

Anyone is free to fork this project, to work on it themselves and fix or add things. So, if you want to try or know someone who might want to, be my guest.

**Comment by ThatGuyIsBack** [comment]
Oh, i was looking forward to seeing this feature. :(
